services:
  admin-service:
    build:
      context: ./admin-service
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_DB: pythonlogin
      SECRET_KEY: jlnjfnsfnbft358134k
    volumes:
      - ./admin-service:/app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: pythonlogin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./shared/database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
